title: Detecting light with the Sense HAT
hero_image: images/banner.png
description: Using the Sense HAT colour sensor
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Sense HAT colour sensor
